# Server settings
server:
    port: 8009
    address: 127.0.0.1
# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
    # DATASOURCE
    datasource:
#        driverClass: com.mysql.jdbc.Driver
                       #        url: jdbc:mysql://127.0.0.1:3306/wcm?useUnicode=true&characterEncoding=utf-8&useSSL=false
                       #        username: root
                       #        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driverClass: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/wcm?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000



